---
name: Lint Code Base
run-name: Linting ${{ github.ref_name }} for ${{ github.triggering_actor }}

permissions: {}

on:
  
  push:
    branches: [main]
  
  pull_request:

# cancel any previously-started, yet still active runs of this workflow on the same branch
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call-super-linter:

    name: Call Super-Linter
    
    permissions:
      contents: read # clone the repo to lint
      statuses: write #read/write to repo custom statuses

    uses: devourer66/super-linter-workflow/.github/workflows/reusable-super-linter.yaml@main
   
    #with: 
    #  runner-labels: '["self-hosted"]'
        
      ### For a DevOps-focused repository. Prevents some code-language linters from running
      ### defaults to false
      # devops-only: false
      
      ### A regex to exclude files from linting
      ### defaults to empty
      # filter-regex-exclude: html/.*
      
